apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cluster-operator
  namespace: redis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-cluster-operator
subjects:
- kind: ServiceAccount
  name: redis-cluster-operator
  namespace: redis
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io